import pandas as pd

country_list = pd.DataFrame([
    ['AARCT', 'Antarctica', 'True'],
    ['ABKHAZ', 'Abkhazia', 'True'],
    ['AFGH', 'Afghanistan', 'False'],
    ['ALB', 'Albania', 'False'],
    ['ALG', 'Algeria', 'False'],
    ['AMSAM', 'American Samoa', 'True'],
    ['ANDO', 'Andorra', 'False'],
    ['ANGOL', 'Angola', 'False'],
    ['ANGUIL', 'Anguilla', 'True'],
    ['ANTA', 'Antigua and Barbuda', 'False'],
    ['ARG', 'Argentina', 'False'],
    ['ARMEN', 'Armenia', 'False'],
    ['ARUBA', 'Aruba', 'True'],
    ['AUST', 'Austria', 'False'],
    ['AUSTR', 'Australia', 'False'],
    ['AZERB', 'Azerbaijan', 'False'],
    ['BAH', 'Bahamas', 'False'],
    ['BAHRN', 'Bahrain', 'False'],
    ['BANDH', 'Bangladesh', 'False'],
    ['BARB', 'Barbados', 'False'],
    ['BELG', 'Belgium', 'False'],
    ['BELZ', 'Belize', 'False'],
    ['BENIN', 'Benin', 'False'],
    ['BERM', 'Bermuda', 'True'],
    ['BHUTAN', 'Bhutan', 'False'],
    ['BIOT', 'British Indian Ocean Territory', 'True'],
    ['BOL', 'Bolivia', 'False'],
    ['BOTS', 'Botswana', 'False'],
    ['BOUV', 'Bouvet Island', 'True'],
    ['BRAZ', 'Brazil', 'False'],
    ['BRUNEI', 'Brunei', 'False'],
    ['BSHZG', 'Bosnia and Herzegovina', 'False'],
    ['BUL', 'Bulgaria', 'False'],
    ['BURMA', 'Myanmar', 'False'],
    ['BURUN', 'Burundi', 'False'],
    ['BVI', 'British Virgin Islands', 'True'],
    ['BYELRS', 'Belarus', 'False'],
    ['CAFR', 'Central African Republic', 'False'],
    ['CAMER', 'Cameroon', 'False'],
    ['CANA', 'Canada', 'False'],
    ['CAYI', 'Cayman Islands', 'True'],
    ['CHAD', 'Chad', 'False'],
    ['CHIL', 'Chile', 'False'],
    ['CHINA', 'China', 'False'],
    ['CHR', 'Christmas Island', 'True'],
    ['COCOS', 'Cocos (Keeling) Islands', 'True'],
    ['COL', 'Colombia', 'False'],
    ['COMOR', 'Comoros', 'False'],
    ['CONGO', 'Congo Republic', 'False'],
    ['COOKIS', 'Cook Islands', 'True'],
    ['COSR', 'Costa Rica', 'False'],
    ['CRTIA', 'Croatia', 'False'],
    ['CUBA', 'Cuba', 'False'],
    ['CVI', 'Cape Verde', 'False'],
    ['CYPR', 'Cyprus', 'False'],
    ['CZREP', 'Czech Republic', 'False'],
    ['DEN', 'Denmark', 'False'],
    ['DOMA', 'Dominica', 'False'],
    ['DOMR', 'Dominican Republic', 'False'],
    ['ECU', 'Ecuador', 'False'],
    ['EGYPT', 'Egypt', 'False'],
    ['ELSAL', 'El Salvador', 'False'],
    ['EQGNA', 'Equatorial Guinea', 'False'],
    ['ERTRA', 'Eritrea', 'False'],
    ['ESTNIA', 'Estonia', 'False'],
    ['ETHPA', 'Ethiopia', 'False'],
    ['FAEROE', 'Faroe Islands', 'True'],
    ['FALK', 'Falkland Islands', 'True'],
    ['FESMIC', 'Micronesia', 'False'],
    ['FGNA', 'French Guiana', 'True'],
    ['FIJI', 'Fiji', 'False'],
    ['FIN', 'Finland', 'False'],
    ['FPOLY', 'French Polynesia', 'True'],
    ['FRA', 'France', 'False'],
    ['GABON', 'Gabon', 'False'],
    ['GAMB', 'Gambia', 'False'],
    ['GFR', 'Germany', 'False'],
    ['GHANA', 'Ghana', 'False'],
    ['GIB', 'Gibraltar', 'True'],
    ['GREECE', 'Greece', 'False'],
    ['GREENL', 'Greenland', 'True'],
    ['GREN', 'Grenada', 'False'],
    ['GRGIA', 'Georgia', 'False'],
    ['GUAD', 'Guadeloupe', 'True'],
    ['GUAM', 'Guam', 'True'],
    ['GUAT', 'Guatemala', 'False'],
    ['GUBI', 'Guinea-Bissau', 'False'],
    ['GUERN', 'Guernsey', 'True'],
    ['GUREP', 'Guinea', 'False'],
    ['GUY', 'Guyana', 'False'],
    ['HAIT', 'Haiti', 'False'],
    ['HEARD', 'Heard and McDonald Islands', 'True'],
    ['HKONG', 'Hong Kong', 'True'],
    ['HON', 'Honduras', 'False'],
    ['HUNG', 'Hungary', 'False'],
    ['ICEL', 'Iceland', 'False'],
    ['ICST', 'Cote d''Ivoire', 'False'],
    ['INDIA', 'India', 'False'],
    ['INDON', 'Indonesia', 'False'],
    ['INTERNATIONAL', 'International', 'False'],
    ['IRAN', 'Iran', 'False'],
    ['IRAQ', 'Iraq', 'False'],
    ['IRE', 'Ireland', 'False'],
    ['ISLEOM', 'Isle of Man', 'True'],
    ['ISRAEL', 'Israel', 'False'],
    ['ITALY', 'Italy', 'False'],
    ['JAMA', 'Jamaica', 'False'],
    ['JAP', 'Japan', 'False'],
    ['JERSEY', 'Jersey', 'True'],
    ['JORDAN', 'Jordan', 'False'],
    ['KAMPA', 'Cambodia', 'False'],
    ['KAZK', 'Kazakhstan', 'False'],
    ['KENYA', 'Kenya', 'False'],
    ['KIRB', 'Kiribati', 'False'],
    ['KIRGH', 'Kyrgyzstan', 'False'],
    ['KOSOVO', 'Kosovo', 'False'],
    ['KUWAIT', 'Kuwait', 'False'],
    ['LAOS', 'Laos', 'False'],
    ['LATV', 'Latvia', 'False'],
    ['LEBAN', 'Lebanon', 'False'],
    ['LESOT', 'Lesotho', 'False'],
    ['LIBER', 'Liberia', 'False'],
    ['LIBYA', 'Libya', 'False'],
    ['LIECHT', 'Liechtenstein', 'False'],
    ['LITH', 'Lithuania', 'False'],
    ['LUX', 'Luxembourg', 'False'],
    ['MACAO', 'Macau', 'True'],
    ['MAH', 'Marshall Islands', 'False'],
    ['MALAG', 'Madagascar', 'False'],
    ['MALAW', 'Malawi', 'False'],
    ['MALAY', 'Malaysia', 'False'],
    ['MALDR', 'Maldives', 'False'],
    ['MALI', 'Mali', 'False'],
    ['MALTA', 'Malta', 'False'],
    ['MARQ', 'Martinique', 'True'],
    ['MAURTN', 'Mauritania', 'False'],
    ['MAURTS', 'Mauritius', 'False'],
    ['MAYOT', 'Mayotte', 'True'],
    ['MCDNIA', 'Macedonia', 'False'],
    ['MEX', 'Mexico', 'False'],
    ['MNTNG', 'Montenegro', 'False'],
    ['MOLDV', 'Moldova', 'False'],
    ['MONAC', 'Monaco', 'False'],
    ['MONGLA', 'Mongolia', 'False'],
    ['MONT', 'Montserrat', 'True'],
    ['MOROC', 'Morocco', 'False'],
    ['MOZAM', 'Mozambique', 'False'],
    ['NAMIB', 'Namibia', 'False'],
    ['NANT', 'Cura?ao', 'True'],
    ['NAURU', 'Nauru', 'False'],
    ['NEPAL', 'Nepal', 'False'],
    ['NETH', 'Netherlands', 'False'],
    ['NEWCAL', 'New Caledonia', 'True'],
    ['NICG', 'Nicaragua', 'False'],
    ['NIGEA', 'Nigeria', 'False'],
    ['NIGER', 'Niger', 'False'],
    ['NIUE', 'Niue', 'True'],
    ['NKOREA', 'North Korea', 'False'],
    ['NOMARI', 'Northern Mariana Islands', 'True'],
    ['NONE', 'None', 'False'],
    ['NORFIS', 'Norfolk Island', 'True'],
    ['NORW', 'Norway', 'False'],
    ['NOTK', 'Not Known', 'False'],
    ['NZ', 'New Zealand', 'False'],
    ['OMAN', 'Oman', 'False'],
    ['PAKIS', 'Pakistan', 'False'],
    ['PALAU', 'Palau', 'False'],
    ['PALEST', 'Palestine', 'False'],
    ['PANA', 'Panama', 'False'],
    ['PAPNG', 'Papua New Guinea', 'False'],
    ['PARA', 'Paraguay', 'False'],
    ['PERU', 'Peru', 'False'],
    ['PHLNS', 'Philippines', 'False'],
    ['PITCIS', 'Pitcairn', 'True'],
    ['POL', 'Poland', 'False'],
    ['PORL', 'Portugal', 'False'],
    ['PST', 'Sao Tome and Principe', 'False'],
    ['PURI', 'Puerto Rico', 'True'],
    ['QATAR', 'Qatar', 'False'],
    ['REUNI', 'Reunion', 'True'],
    ['ROM', 'Romania', 'False'],
    ['RUSS', 'Russia', 'False'],
    ['RWANDA', 'Rwanda', 'False'],
    ['SAARAB', 'Saudi Arabia', 'False'],
    ['SAFR', 'South Africa', 'False'],
    ['SBRTHY', 'Saint Barthélemy', 'True'],
    ['SENEG', 'Senegal', 'False'],
    ['SEYCH', 'Seychelles', 'False'],
    ['SGSSI', 'South Georgia and South Sandwich Islands', 'True'],
    ['SILEN', 'Sierra Leone', 'False'],
    ['SINGP', 'Singapore', 'False'],
    ['SINTMA', 'St. Maarten', 'True'],
    ['SKIT', 'St. Kitts and Nevis', 'False'],
    ['SKOREA', 'South Korea', 'False'],
    ['SLUC', 'Saint Lucia', 'False'],
    ['SLVAK', 'Slovakia', 'False'],
    ['SLVNIA', 'Slovenia', 'False'],
    ['SMARNO', 'San Marino', 'False'],
    ['SOLIL', 'Solomon Islands', 'False'],
    ['SOMAL', 'Somalia', 'False'],
    ['SOSSRT', 'South Ossetia', 'True'],
    ['SOUSUD', 'South Sudan', 'False'],
    ['SPAIN', 'Spain', 'False'],
    ['SPSAH', 'Western Sahara', 'True'],
    ['SRILAN', 'Sri Lanka', 'False'],
    ['STHEL', 'St. Helena', 'True'],
    ['STMART', 'St. Martin', 'True'],
    ['STPM', 'St. Pierre and Miquelon', 'True'],
    ['SUDAN', 'Sudan', 'False'],
    ['SURM', 'Suriname', 'False'],
    ['SVALB', 'Svalbard and Jan Mayen Islands', 'True'],
    ['SVIN', 'St. Vincent and the Grenadines', 'False'],
    ['SWAZD', 'Swaziland', 'False'],
    ['SWED', 'Sweden', 'False'],
    ['SWITZ', 'Switzerland', 'False'],
    ['SYRIA', 'Syria', 'False'],
    ['TADZK', 'Tajikistan', 'False'],
    ['TAI', 'Djibouti', 'False'],
    ['TAIWAN', 'Taiwan', 'False'],
    ['TANZA', 'Tanzania', 'False'],
    ['TCAI', 'Turks and Caicos Islands', 'True'],
    ['THAIL', 'Thailand', 'False'],
    ['TIMOR', 'Timor Leste', 'False'],
    ['TOGO', 'Togo', 'False'],
    ['TOKLAU', 'Tokelau', 'True'],
    ['TONGA', 'Tonga', 'False'],
    ['TRTO', 'Trinidad and Tobago', 'False'],
    ['TUNIS', 'Tunisia', 'False'],
    ['TURK', 'Turkey', 'False'],
    ['TURKM', 'Turkmenistan', 'False'],
    ['TURNC', 'Turkish Republic of Northern Cyprus', 'True'],
    ['TVLU', 'Tuvalu', 'False'],
    ['UAE', 'United Arab Emirates', 'False'],
    ['UGANDA', 'Uganda', 'False'],
    ['UK', 'United Kingdom', 'False'],
    ['UKRN', 'Ukraine', 'False'],
    ['UPVOLA', 'Burkina Faso', 'False'],
    ['URU', 'Uruguay', 'False'],
    ['USA', 'United States', 'False'],
    ['UZBK', 'Uzbekistan', 'False'],
    ['VANU', 'Vanuatu', 'False'],
    ['VCAN', 'Vatican City', 'False'],
    ['VEN', 'Venezuela', 'False'],
    ['VI', 'U.S. Virgin Islands', 'True'],
    ['VIETN', 'Vietnam', 'False'],
    ['WALLIS', 'Wallis and Futuna Islands', 'True'],
    ['WSOMOA', 'Samoa', 'False'],
    ['YEMAR', 'Yemen', 'False'],
    ['YUG', 'Serbia', 'False'],
    ['ZAIRE', 'Democratic Republic of the Congo', 'False'],
    ['ZAMBIA', 'Zambia', 'False'],
    ['ZIMBAB', 'Zimbabwe', 'False']],
    index=['AARCT', 'ABKHAZ', 'AFGH', 'ALB', 'ALG', 'AMSAM', 'ANDO', 'ANGOL', 'ANGUIL', 'ANTA', 'ARG', 'ARMEN',
           'ARUBA', 'AUST', 'AUSTR', 'AZERB', 'BAH', 'BAHRN', 'BANDH', 'BARB', 'BELG', 'BELZ', 'BENIN', 'BERM',
           'BHUTAN', 'BIOT', 'BOL', 'BOTS', 'BOUV', 'BRAZ', 'BRUNEI', 'BSHZG', 'BUL', 'BURMA', 'BURUN', 'BVI',
           'BYELRS', 'CAFR', 'CAMER', 'CANA', 'CAYI', 'CHAD', 'CHIL', 'CHINA', 'CHR', 'COCOS', 'COL', 'COMOR',
           'CONGO', 'COOKIS', 'COSR', 'CRTIA', 'CUBA', 'CVI', 'CYPR', 'CZREP', 'DEN', 'DOMA', 'DOMR', 'ECU',
           'EGYPT', 'ELSAL', 'EQGNA', 'ERTRA', 'ESTNIA', 'ETHPA', 'FAEROE', 'FALK', 'FESMIC', 'FGNA', 'FIJI', 'FIN',
           'FPOLY', 'FRA', 'GABON', 'GAMB', 'GFR', 'GHANA', 'GIB', 'GREECE', 'GREENL', 'GREN', 'GRGIA', 'GUAD',
           'GUAM', 'GUAT', 'GUBI', 'GUERN', 'GUREP', 'GUY', 'HAIT', 'HEARD', 'HKONG', 'HON', 'HUNG', 'ICEL', 'ICST',
           'INDIA', 'INDON', 'INTERNATIONAL', 'IRAN', 'IRAQ', 'IRE', 'ISLEOM', 'ISRAEL', 'ITALY', 'JAMA', 'JAP',
           'JERSEY', 'JORDAN', 'KAMPA', 'KAZK', 'KENYA', 'KIRB', 'KIRGH', 'KOSOVO', 'KUWAIT', 'LAOS', 'LATV',
           'LEBAN', 'LESOT', 'LIBER', 'LIBYA', 'LIECHT', 'LITH', 'LUX', 'MACAO', 'MAH', 'MALAG', 'MALAW', 'MALAY',
           'MALDR', 'MALI', 'MALTA', 'MARQ', 'MAURTN', 'MAURTS', 'MAYOT', 'MCDNIA', 'MEX', 'MNTNG', 'MOLDV',
           'MONAC', 'MONGLA', 'MONT', 'MOROC', 'MOZAM', 'NAMIB', 'NANT', 'NAURU', 'NEPAL', 'NETH', 'NEWCAL', 'NICG',
           'NIGEA', 'NIGER', 'NIUE', 'NKOREA', 'NOMARI', 'NONE', 'NORFIS', 'NORW', 'NOTK', 'NZ', 'OMAN', 'PAKIS',
           'PALAU', 'PALEST', 'PANA', 'PAPNG', 'PARA', 'PERU', 'PHLNS', 'PITCIS', 'POL', 'PORL', 'PST', 'PURI',
           'QATAR', 'REUNI', 'ROM', 'RUSS', 'RWANDA', 'SAARAB', 'SAFR', 'SBRTHY', 'SENEG', 'SEYCH', 'SGSSI',
           'SILEN', 'SINGP', 'SINTMA', 'SKIT', 'SKOREA', 'SLUC', 'SLVAK', 'SLVNIA', 'SMARNO', 'SOLIL', 'SOMAL',
           'SOSSRT', 'SOUSUD', 'SPAIN', 'SPSAH', 'SRILAN', 'STHEL', 'STMART', 'STPM', 'SUDAN', 'SURM', 'SVALB',
           'SVIN', 'SWAZD', 'SWED', 'SWITZ', 'SYRIA', 'TADZK', 'TAI', 'TAIWAN', 'TANZA', 'TCAI', 'THAIL', 'TIMOR',
           'TOGO', 'TOKLAU', 'TONGA', 'TRTO', 'TUNIS', 'TURK', 'TURKM', 'TURNC', 'TVLU', 'UAE', 'UGANDA', 'UK',
           'UKRN', 'UPVOLA', 'URU', 'USA', 'UZBK', 'VANU', 'VCAN', 'VEN', 'VI', 'VIETN', 'WALLIS', 'WSOMOA',
           'YEMAR', 'YUG', 'ZAIRE', 'ZAMBIA', 'ZIMBAB'], columns=('country_code', 'country_name', 'is_terrtory')
)

desc1_dic = {'desc1_name': ['Politically Exposed Person (PEP)', 'Relative or Close Associate (RCA)',
                            'Special Interest Person (SIP)', 'Special Interest Entity (SIE)']}

desc1_list = pd.DataFrame(desc1_dic, index=['1', '2', '3', '4'])

desc2_dic = {'desc2_name': ['Sanctions Lists',
                            'Other Official Lists',
                            'Sanctions Lists',
                            'Other Official Lists',
                            'Terror',
                            'Organised Crime',
                            'Financial Crime',
                            'Trafficking',
                            'Corruption',
                            'War Crimes',
                            'Terror',
                            'Organised Crime',
                            'Financial Crime',
                            'Trafficking',
                            'War Crimes',
                            'Corruption',
                            'Additional Domestic Screening Requirement',
                            'Organised Crime Japan',
                            'Organised Crime Japan',
                            'Enhanced Country Risk',
                            'Enhanced Country Risk',
                            'Other Exclusion Lists',
                            'Other Exclusion Lists',
                            'Tax Crime',
                            'Sanctions Control and Ownership']}

desc2_list = pd.DataFrame(desc2_dic,
                          index=(
                              '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16',
                              '17', '18', '19', '20', '21', '22', '23', '24', '25')
                          )

desc3_dic = {'desc3_name': ['Ship', 'Company', 'Bank', 'Government Entity', 'State Owned Company', 'Charity',
                            'Criminal/Terrorist', 'Religious Sect', 'Country', 'Ship', 'Company', 'Bank',
                            'Government Entity', 'State Owned Company', 'Charity', 'Criminal/Terrorist',
                            'Religious Sect', 'Country', 'Stimulants Control Act Violation', 'Battery or Assault',
                            'Larceny', 'Robbery', 'Extortion', 'Fraud', 'Gambling', 'Bookmaking', 'Intimidation',
                            'Prostitution', 'Possession of gun or knife', 'Sarin and Similar Substances Act Violation',
                            'Unfair Competition', 'Murder or Manslaughter', 'Illegal arrest and confinement',
                            'Kidnapping', 'Defamation', 'Business Obstruction', 'Other', 'Ship', 'Aircraft', 'Aircraft',
                            'Aircraft', 'State Owned Company', 'Bank', 'Lower Threshold', 'Lower Threshold',
                            'Lower Threshold', 'Lower Threshold', 'Lower Threshold', 'OFAC Related - Majority Owned',
                            'OFAC Related - Minority Owned', 'OFAC Related - Ownership Unknown',
                            'EU Related - Minority Owned', 'EU Related - Majority Owned',
                            'EU Related - Ownership Unknown', 'Formerly OFAC Related', 'Formerly EU Related',
                            'OFAC - Regional Sanctions Related - Majority Owned',
                            'OFAC - Regional Sanctions Related - Minority Owned',
                            'OFAC - Regional Sanctions Related - Ownership Unknown',
                            'Formerly OFAC Regional Sanctions Related',
                            'EU - Regional Sanctions Related - Majority Owned',
                            'EU - Regional Sanctions Related - Minority Owned',
                            'EU - Regional Sanctions Related - Ownership Unknown',
                            'Formerly EU Regional Sanctions Related', 'Bank']}

desc3_list = pd.DataFrame(desc3_dic,
                          index=(
                              '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16',
                              '17', '18', '19', '20',
                              '21',
                              '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
                              '37', '38', '39',
                              '40',
                              '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55',
                              '56', '57', '58',
                              '59',
                              '60', '61', '62', '63', '64', '65')
                          )
