"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
# django suit menu setting
from . import admin_settings

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z5!q71!vlzmm&1tq-c-#4$f71tq7j*+t$hid769$e%$8%-4w%*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    #    'bootstrap_admin',
    'suit',
    'polls.apps.PollsConfig',
    'article.apps.ArticleConfig',
    'restapp.apps.RestappConfig',
    'scott.apps.ScottConfig',
    'watchlist.apps.WatchlistConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.baidu',
    'rest_framework',
    'myrestaurants',
    'smartdoc',
    'widget_tweaks',
    'portal',
]

SITE_ID = 1

# add bootstrap_admin setting
# from django.conf import global_settings
# TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS + ('django.core.context_processros.request',)
# BOOTSTRAP_ADMIN_SIDEBAR_MENU = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# BOOTSTRAP_ADMIN_SIDEBAR_MENU = True

WSGI_APPLICATION = 'mysite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        # 'ENGINE': 'django.db.backends.oracle',
        # 'NAME': '10.100.2.35:1521/ORCLPDB',
        # 'USER': 'django',
        # 'PASSWORD': 'django',
    },
    # 'local12c': {
    #     'ENGINE': 'django.db.backends.oracle',
    #     'NAME': 'wkxtedw',
    #     'USER': 'scott',
    #     'PASSWORD': 'tiger',
    #     'HOST': '10.10.22.39',
    #     'PORT': '1521',
    # },
    'watchlist': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': '10.100.2.35:1521/ORCLPDB',
        'USER': 'wluser',
        'PASSWORD': 'wluser',
    },
    'scottdb': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': '10.100.2.35:1521/ORCLPDB',
        'USER': 'scott',
        'PASSWORD': 'tiger',
    },
    # 'wkxtedw_prd': {
    #     'ENGINE': 'django.db.backends.oracle',
    #     'NAME': 'ORCLPDB',
    #     'USER': 'wluser',
    #     'PASSWORD': 'wluser',
    #     'HOST': '10.100.2.35',
    #     'PORT': '1521',
    # },
}

# use multi-database in django
# add by WeizhongTu
DATABASE_ROUTERS = ['mysite.database_router.DatabaseAppsRouter']
DATABASE_APPS_MAPPING = {
    # example:
    # 'app_name':'database_name',
    'scott': 'scottdb',
    'watchlist': 'watchlist',
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static"), ]

# specify media root for user uploaded files,
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Email POP3/SMTP 配置 - QQ邮箱
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25  # 或者 995是设置了 SSL 加密方式
EMAIL_HOST_USER = '501254772@qq.com'  # 发送邮件的邮箱
EMAIL_HOST_PASSWORD = 'poxdyoqdtqzxbhae'  # 在邮箱中设置的客户端授权密码，如果重新设置了新的授权码,直接使用最新的授权码即可
EMAIL_USE_TLS = True  # 这里必须是 True，否则发送不成功
EMAIL_FROM = '501254772@qq.com'  # 收件人看到的发件人
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER  # EMAIL_HOST_USER 默认值为webmaster@localhost 需要修改，否则报501错误

# allauth configuration
# ACCOUNT_SIGNUP_FORM_CLASS = 'myaccounts.forms.SignupForm'

# django-suit configuration start

# suit在admin里设置时间的一个小bug。需要把时间格式指定一下
DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'

# 语言设置成中文
LANGUAGE_CODE = 'zh-Hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_L10N = False
USE_TZ = True

# django-suit configuration end

# LOGIN_URL配置
LOGIN_URL = '/portal/login/'

# LOGIN_URL配置 END
